### ISSUE TITLE
Box.Sdk.Gen.Schemas Task causing ambiguous reference

### ISSUE THREAD

**Issue by joelmeaders** [box/box-dotnet-sdk-gen#227]
When I need to import `Box.Sdk.Gen.Schemas` for Box types the class `Box.Sdk.Gen.Schemas.Task` interferes with `System.Threading.Tasks.Task` everywhere I've got async code. I'm using a namespace alias for the Box Task but I'd prefer not to worry about it in the future.

I'm hoping the Box Task can be renamed, although I understand that would be a breaking change.

For now I'll keep using namespace aliasing or prefixes.

![image](https://github.com/user-attachments/assets/e5f5f27b-cf43-42e4-b1a5-01d627a3c57a)

**Comment by mwwoda** [comment]
Sorry for the inconvenience. Most of the schema names come directly from the specification and we keep them unchanged so that the SDK can reflect the API specification. There may be more conflicts with other namespaces/types (like File) and it is difficult to prevent them all.

You could try adding a [global using](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive#global-modifier) to one of your files (preferably some file with all the global usings) to alias Task like this

`global using Task = System.Threading.Tasks.Task`.

So then you should only need to do it once.

**Comment by joelmeaders** [comment]
That's understandable. Thanks for your time and I'll switch to global using!
